feat: op-contracts `L2OutputOracle.sol` add EOTS info
babylonchain/optimism pull request #4
Opened 2024-05-27 13:42 UTC by lesterli

## Summary

* define `EOTSInfo` in `Types.sol` and update `L2OutputOracle.sol` to receive the data from `op-proposer`
* `npm run snapshots` also generates bytecode of contract

## Test Plan

run `npm run snapshots` under the `packages/contracts-bedrock`

2024-05-27 18:01 UTC, bap2pecs commented on packages/contracts-bedrock/scripts/autogen/generate-snapshots.ts
> +  if (fs.existsSync(abiDir)) {
why adding `existsSync`?

2024-05-27 18:01 UTC, bap2pecs commented on packages/contracts-bedrock/src/L1/L2OutputOracle.sol
> +            require(_eotsInfos[i].fpBtcPk != bytes32(0), "L2OutputOracle: EOTSInfo.fpBtcPk cannot be zero");
let's add a TODO comment so we know we will add a call here

2024-05-27 18:01 UTC, bap2pecs commented on packages/contracts-bedrock/test/invariants/L2OutputOracle.t.sol
> +        oracle.proposeL2Output(_outputRoot, _l2BlockNumber, _l1BlockHash, _l1BlockNumber, _eotsInfos);
why not just use `_defaultEotsInfos` here?

2024-05-28 00:19 UTC, SebastianElvis approved these changes

2024-05-28 00:19 UTC, SebastianElvis commented on packages/contracts-bedrock/src/L1/L2OutputOracle.sol
> +        Types.EOTSInfo[] calldata _eotsInfos
docstring needs to be updated w.r.t. `_eotsInfos` as well

2024-05-31 16:43 UTC, bap2pecs requested changes
won't touch l2oo per https://github.com/ethereum-optimism/specs/discussions/218

2024-06-05 00:18 UTC, closed without merging